name: build container image
on:
  push:
    branches:
      - 'pre-nodes'
      - 'update/ci/docker/*'
      - 'update/docker/*'
      - 'dev/ci/docker/*'
      - 'dev/docker/*'
    paths:
      - 'pyproject.toml'
      - '.dockerignore'
      - 'invokeai/**'
      - 'docker/Dockerfile'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  docker:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - cuda
          - cpu
        include:
          - flavor: cuda
            pip-extra-index-url: ''
          - flavor: cpu
            pip-extra-index-url: 'https://download.pytorch.org/whl/cpu'
    runs-on: self-hosted
    name: ${{ matrix.flavor }}
    env:
      PLATFORMS: 'linux/amd64,linux/arm64'
      DOCKERFILE: 'docker/Dockerfile'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=sha,enable=true,prefix=sha-,format=short
          flavor: |
            latest=${{ matrix.flavor == 'cuda' && github.ref == 'refs/heads/main' }}
            suffix=-${{ matrix.flavor }},onlatest=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: PIP_EXTRA_INDEX_URL=${{ matrix.pip-extra-index-url }}
          cache-from: |
            type=gha,scope=${{ github.ref_name }}-${{ matrix.flavor }}
            type=gha,scope=main-${{ matrix.flavor }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ matrix.flavor }}
          
      - name: Set container SHA
        id: set-container-sha
        run: |
          echo "::set-output name=CONTAINER_SHA::${{ steps.build-push.outputs.digest }}"
          echo $CONTAINER_SHA  
      # https://github.com/orgs/community/discussions/25768#discussioncomment-3249183
      # - name: downcase REPO
      #   run: |
      #     echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}      
      - uses: paperspace/deploy-action@v1.2
        name: Deploy to Paperspace
        id: deploy
        env:
          PAPERSPACE_API_KEY: ${{ secrets.PAPERSPACE_API_KEY }}
          CONTAINER_SHA: ${{ steps.set-container-sha.outputs.CONTAINER_SHA }}
        with:
          projectId: pioiimjvdsx
          # image: ghcr.io/${{ github.repository }}:latest@${{ steps.build-push.outputs.digest }}
          image: ghcr.io/gradient-ai/invokeai:latest@${{ steps.build-push.outputs.digest }}
